export const mockHackerService = {
  getHackerById: jest.fn().mockResolvedValue({
    name: "John Doe",
    nickname: "Johnny",
    created_at: "2023-09-15",
    type: "hacker",
    image: "https://example.com/image.jpg",
    github: "johndoe",
    linkedin: "johndoe",
    id: 1,
    food_restrictions: "None",
    birthdate: "1990-01-01",
    email: "john.doe@example.com",
    telephone: "1234567890",
    address: "123 Main St",
    shirt_size: "M",
    is_verified: true,
    code: "ABC123XYZ456",
    config: {
      default_lang: "en-US",
      id: 82,
      comercial_notifications: true,
      recive_notifications: true,
      terms_and_conditions: true,
    },
    how_did_you_meet_us: "Internet",
    location: "USA",
    cv: "https://example.com/cv.pdf",
    study_center: "University of Example",
    studies: "Computer Science",
    banned: 0,
  }),
};
