name: deploy on VPS
on:
  push:
    branches:
      - main
      - integration
      - FRONT-169-Crear-tests-de-frontend
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      # Checkout the Repo
      - uses: actions/checkout@v2

      # Install Node 12
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 18

      # Install dependencies
      - run: npm install

      # Run tests
      - run: npm run test -- --watchAll=false --ci --passWithNoTests --silent 
